import os
import sys
import json
import shutil
import tempfile
import unittest
from unittest.mock import patch, MagicMock

SERVER_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "server"))
if SERVER_DIR not in sys.path:
    sys.path.insert(0, SERVER_DIR)

from state_store import db
from tools.local_builder_tool import (
    execute_local_builder,
    apply_surgical_patch,
    resolve_safe_worktree_path,
)


class TestIssue28LocalBuilderOmniRouteFallback(unittest.TestCase):
    """
    Testes de regressão e aceitação da Issue #28:
    Circuit breaker com re-roteamento automático para nuvem via OmniRoute em caso de OOM,
    timeout ou indisponibilidade do Ollama no Local Builder.
    """

    def setUp(self):
        self.test_dir = tempfile.mkdtemp(prefix="cockpit_test_issue28_")
        self.slice_id = "slice-1"
        self.worktree_dir = os.path.join(self.test_dir, ".worktrees", self.slice_id)
        os.makedirs(self.worktree_dir, exist_ok=True)
        db.switch_current_project("default")
        db.set_local_worker_config({
            "enabled": True,
            "delegate_styles_to_cloud": False,
            "omniroute_fallback": True
        })
        if hasattr(db, "reset_local_worker_attempts"):
            db.reset_local_worker_attempts(self.slice_id)

    def tearDown(self):
        db.switch_current_project("default")
        if os.path.exists(self.test_dir):
            shutil.rmtree(self.test_dir, ignore_errors=True)

    @patch("tools.local_builder_tool.call_omniroute_llm")
    @patch("tools.local_builder_tool.call_local_llm")
    def test_01_oom_triggers_automatic_omniroute_rerouting(self, mock_local_llm, mock_omniroute_llm):
        """
        Critério a e b:
        Quando Ollama falha com GPU out of memory, re-roteia automaticamente para o OmniRoute,
        aplica o patch retornado pelo modelo cloud e marca routed_to_cloud no resultado.
        """
        mock_local_llm.side_effect = RuntimeError("CUDA error: GPU out of memory (OOM)")
        mock_omniroute_llm.return_value = {
            "patch": "<<<<<<< SEARCH\ndef calculate():\n    return 0\n=======\ndef calculate():\n    return 42  # Generated by OmniRoute Cloud\n>>>>>>>",
            "tokens": 64,
            "duration_ms": 320,
            "model": "auto",
            "provider": "omniroute"
        }

        target_file = "src/calc.py"
        target_abs = os.path.join(self.worktree_dir, target_file)
        os.makedirs(os.path.dirname(target_abs), exist_ok=True)
        with open(target_abs, "w", encoding="utf-8") as f:
            f.write("def calculate():\n    return 0\n")

        res = execute_local_builder(
            slice_id=self.slice_id,
            instruction="Retorne 42 na função calculate",
            target_file=target_file,
            repo_root=self.test_dir
        )

        # 1. Verifica que a chamada ao OmniRoute ocorreu
        self.assertTrue(mock_omniroute_llm.called, "call_omniroute_llm deve ter sido acionado após OOM local.")
        
        # 2. Verifica contrato de resultado com delegação para nuvem
        self.assertEqual(res.get("status"), "DELIVERED")
        self.assertTrue(res.get("routed_to_cloud"), "Resultado deve indicar routed_to_cloud=True.")
        self.assertEqual(res.get("cloud_provider"), "omniroute")
        self.assertEqual(res.get("target_file"), target_file)
        self.assertGreaterEqual(res.get("hunks_applied", 0), 1)

        # 3. Verifica que o patch da nuvem foi aplicado no arquivo
        with open(target_abs, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn("return 42  # Generated by OmniRoute Cloud", content)
        self.assertNotIn("return 0\n", content)

    @patch("tools.local_builder_tool.call_omniroute_llm")
    @patch("tools.local_builder_tool.call_local_llm")
    def test_02_timeout_and_connection_refused_trigger_rerouting(self, mock_local_llm, mock_omniroute_llm):
        """
        Critério a:
        Valida que tanto timeout quanto connection refused no Ollama acionam
        o re-roteamento automático para o OmniRoute.
        """
        # Caso A: Timeout local
        mock_local_llm.side_effect = TimeoutError("Ollama inference timed out after 120s")
        mock_omniroute_llm.return_value = {
            "patch": "```python\n# Cloud generation after timeout\ndef process():\n    return True\n```",
            "tokens": 40,
            "duration_ms": 250,
            "model": "gemini-1.5-flash",
            "provider": "omniroute"
        }

        target_file = "src/process.py"
        res_timeout = execute_local_builder(
            slice_id=self.slice_id,
            instruction="Crie a função process",
            target_file=target_file,
            repo_root=self.test_dir
        )
        self.assertEqual(res_timeout.get("status"), "DELIVERED")
        self.assertTrue(res_timeout.get("routed_to_cloud"))
        self.assertTrue(mock_omniroute_llm.called)

        # Caso B: Connection refused (daemon offline na porta 11434)
        mock_omniroute_llm.reset_mock()
        mock_local_llm.side_effect = ConnectionRefusedError("[Errno 111] Connection refused on 11434")
        mock_omniroute_llm.return_value = {
            "patch": "```python\n# Cloud generation after offline local daemon\ndef process():\n    return 'online'\n```",
            "tokens": 45,
            "duration_ms": 180,
            "model": "claude-3-5-haiku",
            "provider": "omniroute"
        }

        res_conn = execute_local_builder(
            slice_id=self.slice_id,
            instruction="Atualize a função process para retornar 'online'",
            target_file=target_file,
            repo_root=self.test_dir
        )
        self.assertEqual(res_conn.get("status"), "DELIVERED")
        self.assertTrue(res_conn.get("routed_to_cloud"))
        self.assertTrue(mock_omniroute_llm.called)

    @patch("tools.local_builder_tool.call_omniroute_llm")
    @patch("tools.local_builder_tool.call_local_llm")
    def test_03_telemetry_and_pulse_notification_on_cloud_reroute(self, mock_local_llm, mock_omniroute_llm):
        """
        Critério c:
        Notificar o dashboard do Cockpit e o Zeus Chat sobre a delegação automática à nuvem,
        registrando na telemetria/pulse ou nos logs da tarefa com mensagem explícita:
        '[LocalBuilder] Re-roteando tarefa para nuvem via OmniRoute devido a falha local...'.
        """
        mock_local_llm.side_effect = RuntimeError("GPU out of memory")
        mock_omniroute_llm.return_value = {
            "patch": "```python\ndef run_task():\n    return 'success'\n```",
            "tokens": 30,
            "duration_ms": 150,
            "model": "auto",
            "provider": "omniroute"
        }

        target_file = "src/task.py"
        execute_local_builder(
            slice_id=self.slice_id,
            instruction="Crie função run_task",
            target_file=target_file,
            repo_root=self.test_dir
        )

        # 1. Verifica mensagem gravada no state store (steering_messages / Zeus Chat & Dashboard)
        state = db.get_state()
        steering_msgs = state.get("steering_messages", [])
        reroute_msgs = [
            m for m in steering_msgs
            if "Re-roteando tarefa para nuvem via OmniRoute" in m.get("text", "")
            and target_file in m.get("text", "")
        ]
        self.assertGreater(
            len(reroute_msgs), 0,
            "Deve registrar mensagem de telemetria em steering_messages sobre o re-roteamento."
        )
        self.assertIn("GPU out of memory", reroute_msgs[-1]["text"])

        # 2. Verifica pulse atualizado do par correspondente
        pairs = state.get("pairs_3x3", [])
        pair_1 = next((p for p in pairs if p["id"] == 1), None)
        self.assertIsNotNone(pair_1)
        self.assertEqual(pair_1.get("current_slice_id"), self.slice_id)

    @patch("tools.local_builder_tool.call_omniroute_llm")
    @patch("tools.local_builder_tool.call_local_llm")
    def test_04_fallback_to_scaffold_only_when_omniroute_also_fails(self, mock_local_llm, mock_omniroute_llm):
        """
        Critério d:
        Fallback para scaffold/mock apenas caso o OmniRoute também falhe ou esteja indisponível.
        """
        # Ambos falham: Ollama com OOM e OmniRoute com ConnectionRefused / 500
        mock_local_llm.side_effect = RuntimeError("GPU out of memory")
        mock_omniroute_llm.side_effect = RuntimeError("OmniRoute gateway unreachable (port 20128 connection refused)")

        target_file = "src/dashboard.html"
        res = execute_local_builder(
            slice_id=self.slice_id,
            instruction="Crie a dashboard com #metrics e #charts",
            target_file=target_file,
            repo_root=self.test_dir
        )

        self.assertEqual(res.get("status"), "DELIVERED")
        self.assertIn("scaffold fallback", res.get("diff_summary", ""))
        self.assertFalse(res.get("routed_to_cloud", False))

        target_abs = os.path.join(self.worktree_dir, target_file)
        self.assertTrue(os.path.exists(target_abs))
        with open(target_abs, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn("<!DOCTYPE html>", content)
        self.assertIn("id=\"metrics\"", content)

    @patch("tools.local_builder_tool.call_omniroute_llm")
    @patch("tools.local_builder_tool.call_local_llm")
    def test_05_fallback_to_scaffold_when_omniroute_disabled(self, mock_local_llm, mock_omniroute_llm):
        """
        Critério d:
        Quando omniroute_fallback estiver desabilitado (False) na configuração,
        não deve invocar OmniRoute e sim degradar imediatamente para scaffold/mock.
        """
        db.set_local_worker_config({
            "enabled": True,
            "delegate_styles_to_cloud": False,
            "omniroute_fallback": False
        })
        mock_local_llm.side_effect = RuntimeError("GPU out of memory")

        target_file = "src/widget.py"
        res = execute_local_builder(
            slice_id=self.slice_id,
            instruction="Crie o widget de controle",
            target_file=target_file,
            repo_root=self.test_dir
        )

        self.assertFalse(mock_omniroute_llm.called, "OmniRoute não deve ser chamado quando desabilitado.")
        self.assertEqual(res.get("status"), "DELIVERED")
        self.assertIn("scaffold fallback", res.get("diff_summary", ""))


if __name__ == "__main__":
    unittest.main()
